---

- name: create locale ja_JP.UTF-8
  shell: locale-gen ja_JP.UTF-8
  become: yes
  become_method: sudo

- name: setup apt for postgresql 9.4 (add pgdg.list)
  copy: src=pgdg.list dest=/etc/apt/sources.list.d/pgdg.list
  become: yes
  become_method: sudo

- name: setup apt for postgresql 9.4 (add apt-key)
  apt_key: url=https://www.postgresql.org/media/keys/ACCC4CF8.asc state=present
  become: yes
  become_method: sudo

- name: install postgresql 9.4
  apt: name={{ item }} update_cache=yes
  with_items:
    - postgresql-9.4
    - postgresql-client-9.4
    - postgresql-contrib-9.4
    - libpq-dev
    - postgresql-server-dev-9.4
    - python-psycopg2
  become: yes
  become_method: sudo
